using Kebapi.Domain;
using System.Collections.Generic;

namespace Kebapi.DataAccess.Sql
{
    /// <summary>
    /// Dal SQL for populating the database with sample test data.
    /// </summary>
    // These could go into a resource file (resx) to allow changes to the SQL
    // without recompilation. However resource files really are more geared to
    // i18n, their UI isn't great for SQL, it limits string interpolation and
    // other language editing features like syntax highlighting, it's "yet another
    // place" where SQL might be stored, and it adds another layer that the
    // framework must process and deal with (no matter how optimised).
    //
    // If avoiding recompilation of the entire app is a must, these could go in
    // a separate assembly. Arguably however, changes to core SQL aren't likely
    // to be off the cuff affairs requiring little oversight.
    //
    // Another alternative is to implement as stored procedures on the database
    // server, but that brings other advantages/disadvantages.
    internal static class SampleDataSql
    {
        internal static Dictionary<string, string> Populate = new()
        {
            {
                $"Table.{DbTable.LookupRoles}",
                @$"
                    INSERT INTO [{DbTable.LookupRoles}] ([id], [role]) 
                    VALUES 
                        ({(byte)User.Role.Admin}, 'Admin'),
                        ({(byte)User.Role.User}, 'User'), 
                        ({(byte)User.Role.Everyone}, 'Everyone')
                ;"
            },
            {
                $"Table.{DbTable.LookupUserAccountStatus}",
                @$"
                    INSERT INTO [{DbTable.LookupUserAccountStatus}] ([id], [status]) 
                    VALUES 
                        ({(byte)User.AccountStatus.Active}, 'Active'),
                        ({(byte)User.AccountStatus.Inactive}, 'Inactive')
                ;"
            },
            {
                $"Table.{DbTable.Users}",
                @$"
                    SET IDENTITY_INSERT [{DbTable.Users}] ON;

                    INSERT INTO [{DbTable.Users}] 
                        ([id], [username], [name], [surname], [email], [password_hash], [role_id], [account_status_id]) 
                    VALUES 
                        -- old test hashes for nodejs version generated at: https://bcrypt-generator.com/
                        -- new test hashes for .net version generated by HashingService.
                        -- plain pwd: bob1      rounds: 8   old hash used in nodejs version: $2y$08$9V7mg7B1O.m7vUTIizdTH.DjyiFOjPEa4tN/cQv9vwTv7.qbs7nu.
                        -- new hash used in .net version: SHA512.10000.Nj6DadyiCvfZLjTcpUwIpB9VFs5INaWU.f2P9jPNImS2si7dH/co2FtaGP24FeZdiJWUjMrsiHQs=
                        (1, 'aard', 'Bob', 'Smithers', 'aard@smithers.com', 'SHA512.10000.Nj6DadyiCvfZLjTcpUwIpB9VFs5INaWU.f2P9jPNImS2si7dH/co2FtaGP24FeZdiJWUjMrsiHQs=', {(byte)User.Role.Admin}, {(byte)User.AccountStatus.Active}),
                        -- plain pwd: lucy1     rounds: 8   old hash used in nodejs version: $2y$08$NrLM7FPM9K/iYhCnnAL26.QWBkUTdr4aN9m0DVelbZvRMz/A3Qf5q
                        -- new hash used in .net version: SHA512.10000.EoKM524CaxBu6gYbFtLxnyRj8DFC1uzn.e6ayJRzxxU/yusewIXvZIrgNSqM4EOlAdrUGq/DIn7Q=
                        (2, 'Babs', 'Lucy', 'Matthews', 'babs@matthews.co.uk', 'SHA512.10000.EoKM524CaxBu6gYbFtLxnyRj8DFC1uzn.e6ayJRzxxU/yusewIXvZIrgNSqM4EOlAdrUGq/DIn7Q=', {(byte)User.Role.User}, {(byte)User.AccountStatus.Active}),
                        -- plain pwd: percy1    rounds: 8   old hash used in nodejs version: $2y$08$wCDuc5ZmfwMp28GPmxP5uOejOvz3mkogp5KF3nkTwez3K8L8q.yFC
                        -- new hash used in .net version: SHA512.10000.2lDLA7xvBTQsQKLrO0LODvfvMAI7A3NQ.batkh7HvnnknWDaoou44s+cjUsEheoF3rHzSQBDnu5A=
                        (3, 'MeatyMan', 'Percy', 'Archibald-Hyde', 'meatyman@archibald-hyde.eu', 'SHA512.10000.2lDLA7xvBTQsQKLrO0LODvfvMAI7A3NQ.batkh7HvnnknWDaoou44s+cjUsEheoF3rHzSQBDnu5A=', {(byte)User.Role.User}, {(byte)User.AccountStatus.Active}),
                        -- plain pwd: farquhar1 rounds: 8   old hash used in nodejs version: $2y$08$Zz23B5j431OdTEP2oW0jDuc7krZkdNIXgK.cIILnQuZDTD2RKq2q6
                        -- new hash used in .net version: SHA512.10000.w3qFesjjYxLLe8kWsmHXrjgdb2zs6Bnu.gnvwkJA8kgnluEniWWr5smZoF22WXNIo45YEAj2eG4I=
                        (4, 'kAb0000B', 'Farquhar', 'Rogers', 'kAb0000B@rogers.me', 'SHA512.10000.w3qFesjjYxLLe8kWsmHXrjgdb2zs6Bnu.gnvwkJA8kgnluEniWWr5smZoF22WXNIo45YEAj2eG4I=', {(byte)User.Role.User}, {(byte)User.AccountStatus.Active}),
                        -- plain pwd: gigi1 rounds: 8   old hash used in nodejs version: $2y$08$jjz84rVjTkq0TrGQkxYKdejiCLLSzUdPLQTdsrDLDl.PeB/b0xv5y
                        -- new hash used in .net version: SHA512.10000.JyzLzIH7SW9MkoCr6M4bMoqSAnk86HZ8.1UUkgP2aalserksRXJu+8tS0lSWr5T+r5gV05AIJI38=
                        (5, 'ItsGigi', 'Gigi', 'McInactive-User', 'gigi@gmail.com', 'SHA512.10000.JyzLzIH7SW9MkoCr6M4bMoqSAnk86HZ8.1UUkgP2aalserksRXJu+8tS0lSWr5T+r5gV05AIJI38=', {(byte)User.Role.User}, {(byte)User.AccountStatus.Inactive})
                    ;

                    SET IDENTITY_INSERT {DbTable.Users} OFF;
                "
            },
            {
                $"Table.{DbTable.Media}",
                @$"
                    SET IDENTITY_INSERT [{DbTable.Media}] ON;

                    INSERT INTO [{DbTable.Media}] 
                        ([id], [user_id], [media_path]) 
                    VALUES 
                        (1, 1, 'image\1.jpg'),
                        (2, 1, 'image\2.jpg'),
                        (3, 1, 'image\3.jpg'),
                        (4, 1, 'image\4.jpg'),
                        (5, 1, 'image\5.jpg'),
                        (6, 1, 'image\6.jpg'),
                        (7, 1, 'image\7.jpg'),
                        (8, 1, 'image\8.jpg'),
                        (9, 1, 'image\9.jpg'),
                        (10, 1, 'image\10.jpg')
                    ;

                    SET IDENTITY_INSERT [{DbTable.Media}] OFF;
                "
            },
            {
                $"Table.{DbTable.Venues}",
                @$"
                    SET IDENTITY_INSERT [{DbTable.Venues}] ON;

                    INSERT INTO [{DbTable.Venues}]
                        ([id], [name], [geo_lat], [geo_lng], [address], [rating], [main_media_id]) 
                    VALUES 
                        -- The original pre-latitude/longitude grid coordinates are kept commented out
                        -- below because they are referred to in related materials, and are a baseline
                        -- for sourcing the latitudes and longitudes that replace them. (They are
                        -- relative points from which latitudes and longitudes can be obtained.)
                        /*
                        (1, 'Splendid Kebabs', 2, 1, '42 Bla Avenue, Madrid', 4, 1),
                        (2, 'The Kebaberie', 5, 2, '101 Santa Monica Way, Madrid', 3, 2),
                        (3, 'Meats Peeps', 7, 8, '276 Rita St, Madrid', 4, 3),
                        (4, 'The Rotisserie', 1, 9, '7 Rick Road, Madrid', 3, 4),
                        (5, 'The Dirty One', 4, 1, '10 Banana Place, Madrid', 5, 5),
                        (6, 'Bodrum Conundrum', 5, 5, '55 High Five Drive, Madrid', 2, 6),
                        (7, 'Korner Kebab', 3, 1, '11b Indy Place, Madrid', 1, 7),
                        (8, 'Star Kebab', 3, 6, '222 Crispy Crescent, Madrid', 4, 8),
                        (9, 'Kebab Slab', 5, 7, '5 Five Drive, Madrid', 3, 9),
                        (10, 'Turku Kebabi', 9, 0, '21B Baker Street, Madrid', 5, 10)
                        */
                        (1, 'Splendid Kebabs', 40.42795262756104, -3.7116578794243558, '42 Bla Avenue, Madrid', 4, 1),
                        (2, 'The Kebaberie', 40.42207211170083, -3.6853078577300646, '101 Santa Monica Way, Madrid', 3, 2),
                        (3, 'Meats Peeps', 40.38268004589479, -3.6687681075408354, '276 Rita St, Madrid', 4, 3),
                        (4, 'The Rotisserie', 40.37640325727719, -3.719853607604965, '7 Rick Road, Madrid', 3, 4),
                        (5, 'The Dirty One', 40.42847531520142, -3.6942342494440914, '10 Banana Place, Madrid', 5, 5),
                        (6, 'Bodrum Conundrum', 40.40144154092246, -3.684389293040381, '55 High Five Drive, Madrid', 2, 6),
                        (7, 'Korner Kebab', 40.4286059864768, -3.7027314877103286, '11b Indy Place, Madrid', 1, 7),
                        (8, 'Star Kebab', 40.39588554537884, -3.702757060605783, '222 Crispy Crescent, Madrid', 4, 8),
                        (9, 'Kebab Slab', 40.38980610735031, -3.6858484147628663, '5 Five Drive, Madrid', 3, 9),
                        (10, 'Turku Kebabi', 40.43500856795563, -3.650975581906885, '21B Baker Street, Madrid', 5, 10)
                    ;

                    SET IDENTITY_INSERT {DbTable.Venues} OFF;
                "
            },
            {
                $"Table.{DbTable.UserFavouriteVenues}",
                @$"
                    SET IDENTITY_INSERT [{DbTable.UserFavouriteVenues}] ON;

                    INSERT INTO [{DbTable.UserFavouriteVenues}]
                        ([id], [user_id], [venue_id]) 
                    VALUES 
                        (1, 1, 5), -- aard has favourited The Dirty One
                        (2, 1, 4), -- aard has favourited The Rotisserie
                        (3, 2, 3), -- Babs has favourited Meats Peeps
                        (4, 2, 4), -- Babs has favourited The Rotisserie
                        (5, 2, 2), -- Babs has favourited The Kebaberie
                        (6, 4, 6)  -- kAb0000B has Bodrum Conundrum
                    ;

                    SET IDENTITY_INSERT {DbTable.UserFavouriteVenues} OFF;
                "
            },
        };
    }
}
